from pathlib import Path
from PIL import Image
import json,re
B=Path(__file__).resolve().parents[1];P=B/'public';pages=json.loads((B/'research/pages.json').read_text());images=json.loads((B/'research/images.json').read_text());byurl={a['url']:a for a in images if a.get('path')}
def props(page,part):
 p=next(x for x in pages if x['path']==page)
 return next(x['layer']['data']['componentProps'] for x in p['state'][0]['version']['sections'] if part in x['title'])
def asset(src):
 a=dict(byurl[src]);a['width'],a['height']=Image.open(P/a['path'].lstrip('/')).size
 return a
refs=props('referenzen','Projekte')['projects'];projects=[]
configs=[('wincklerstrasse','Wincklerstraße','Hamburg-Neustadt','Fassadensanierung am Michel · Arbeits- und Schutzgerüst mit Netzverkleidung','facades','Fassaden',['a73b5c5d7270','600ab0803864']),('berliner-tor','Berliner Tor 9','Hamburg-St. Georg','Arbeits- und Schutzgerüst · 2.000 m². Bauaufzug und verfahrbares Wetterschutzdach.','facades','Fassaden',['ed34b54d23e6','547e2ce9d12c','f76a0dcc6a22','79b8687c9012']),('adolfstrasse','Adolfstraße 14–16','Ahrensburg','Arbeits- und Schutzgerüst · 3.000 m². Neubau inklusive Dachfangerüst.','weather','Dach & Wetterschutz',['b0309c782dbb']),('rupertistrasse','Rupertistraße 4, 6, 8 & 3, 5, 7','Hamburg-Altona','Gesamtgerüstfläche · 2.650 m². Aufstockung inklusive Dachfangerüst.','facades','Fassaden',['d322fdccb5ff']),('grindelallee','Grindelallee 44','Hamburg-Eimsbüttel','Arbeits- und Schutzgerüst mit integriertem Fußgängertunnel.','facades','Fassaden',['adee3a73f002']),('eurogate','Containerterminal Eurogate','Hamburg-Waltershof','Hängegerüste und Sonderkonstruktionen an einer Verladebrücke.','industry','Industrie & Sonderbau',['3e063a7af280','b86b50f6b3f3'])]
byhash={a['path'].split('/')[-1].split('.')[0]:a for a in images if a.get('path')}
for id,title,location,task,category,label,keys in configs:
 shots=[asset(byhash[k]['url']) for k in keys]
 projects.append(dict(categories=[category]+(['weather'] if id=='berliner-tor' else []),id=id,title=title,location=location,task=task,planning=location,category=category,categoryLabel=label,cover=shots[0],images=shots,source='https://www.j-werner-geruestbau.de/referenzen'))
people=props('kontakt','Ansprechpartner')['members']
for a in people:a['image']=asset(a['image']['src'])['path']
company={'services':props('leistungen','Kernleistungen')['serviceItems'],'extras':props('leistungen','Zusatzleistungen')['items'],'steps':props('home','So arbeiten wir')['steps'],'jobs':props('karriere','Vorteile')['jobs'],'benefits':props('karriere','Vorteile')['benefits'],'faq':props('karriere','FAQ')['items'],'impressum':props('impressum','Inhalt')['blocks']}
for a in company['services']+company['extras']:a['image']=asset(a['image']['src'])['path']
(P/'data').mkdir(exist_ok=True);(P/'projekte').mkdir(exist_ok=True)
for name,data in [('projects',projects),('people',people),('company',company)]: (P/f'data/{name}.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
# Collect human-readable source text, including all public pages. Keep raw state out of Git.
md='# J. Werner Gerüstbau — Website-Inventar\n\nStand: 5. Oktober 2026. Primärquelle: https://www.j-werner-geruestbau.de/. 11 öffentlich verlinkte Seiten gesammelt. Sichtbarer Text wird unten vollständig je Seite archiviert; Angaben sind Unternehmensangaben, keine unabhängige Prüfung.\n\n'
md+='## Stammdaten\n\nJ. WERNER GERÜSTBAU GmbH & Co. KG · seit 1976 · Werner-Siemens-Straße 105, 22113 Hamburg · 040 732 10 91 · info@j-werner-geruestbau.de.\n\n## Medien\n\n60 Bilddateien aus 61 gefundenen Originaladressen; eine nicht als Rasterbild lesbare Datei ausgelassen. Alle heruntergeladenen Bilder sind unter `public/assets/images/` archiviert. WebP maximal 2.400 Pixel lange Kante, Vorschaubilder nur im Filmstreifen, große Originaldateien im sichtbaren Portfolio. Original-PNG-Logo separat. Zwei Original-MP4-Dateien lokal übernommen, unverändert: Vorschau 3.172.418 Byte, vollständiger Film 12.983.229 Byte. Herkunft: öffentliche Hero-Konfiguration der Homepage. Bild- und Filmrechte stammen aus dem bestehenden Unternehmensauftritt; Rechtezuordnung vor endgültigem Domainwechsel bestätigen.\n\n## Referenzen\n\n'
for p in projects:md+=f"- **{p['title']}**, {p['location']}: {p['task']} {len(p['images'])} zugeordnete Aufnahmen.\n"
md+='\nBerliner Tor mit Wetterschutzdach ist dieselbe Gesamtmaßnahme und wird nicht als weiteres unabhängiges Projekt gezählt. Die konkrete Jahreszahl und Auftraggeber fehlen in der Quelle; keine ergänzt. Andere Servicebilder werden nicht mit erfundenen Projektnamen ausgestattet.\n\n## Eignung und offene Punkte\n\n- Quelle nennt DIN 18451, Mitgliedschaft im Bundesverband Gerüstbau, Präqualifikation VOB und VHV-Betriebshaftpflicht. Keine aktuelle PQ-Nummer, Gültigkeitsbelege oder Versicherungssummen gefunden. Website verweist daher auf anforderbare Nachweise und vermeidet erfundene Zertifikate.\n- Bewertungen widersprüchlich: Homepage 4,9/5,0, Kundenstimmen 5,0/5,0. Nicht als geprüfte Bewertung im Entwurf übernommen.\n- 30+ Fachkräfte, 98 % Termintreue und 500+ Projekte/Jahr sind nicht extern verifizierte Marketingangaben. Kein neuer Statistikblock.\n- Die aktive Leistungsliste enthält 9 Kernleistungen. Ein alternatives, nicht aktives Konfigurationsfeld enthält zusätzlich Offshore-Gerüste. Offshore wird nicht als neue bestätigte Leistung veröffentlicht.\n- Aktuelles Impressum nennt Reno Maack, Steve Mutz und Axel Seehafer als Geschäftsführer der persönlich haftenden Gruppenwerk Projektentwicklung GmbH. Teamdarstellung nennt Reno und Steve. Kein Widerspruch aus alter Cache-Seite übernommen.\n- Das Quell-Impressum zitiert noch TMG; neuer Entwurf übernimmt Register- und Unternehmensdaten ohne veraltete Paragraphenüberschrift.\n- Alte Datenschutzseite beschreibt Onepage, Google-Dienste und Consent. Neuer Entwurf nutzt eigene Cloudflare-Medien, lokale Schriften und kein Tracking; die Datenschutzhinweise beschreiben genau diesen technischen Stand.\n- Kontakt und Bewerbung bereiten E-Mails vor. Kein unbestätigtes Resend-Postfach oder WhatsApp-Platzhalter von Werner Bau übernommen.\n\n## Vollständiger Seiteninhalt\n\n'
for page in pages:md+=f"### {page['path']}\n\nQuelle: {page['url']}\n\n```text\n{page['text']}\n```\n\n"
(B/'research/WEBSITE-INVENTAR.md').write_text(md.rstrip()+"\n")
(B/'research/MEDIEN-INVENTAR.json').write_text(json.dumps(images,ensure_ascii=False,indent=2))
print('Catalog:',len(projects),'projects,',sum(len(p['images']) for p in projects),'photos,',len(people),'people')
