import assert from 'node:assert/strict';import{readFile,access}from'node:fs/promises';import{execFileSync}from'node:child_process';
const projects=JSON.parse(await readFile('public/data/projects.json')),people=JSON.parse(await readFile('public/data/people.json'));assert.equal(projects.filter(p=>p.kind!=='insight').length,6);assert.equal(new Set(projects.map(p=>p.id)).size,projects.length);assert.equal(people.length,7);
for(const p of projects){assert.match(p.source,/^https:\/\/www\.j-werner-geruestbau\.de\//);for(const image of p.images){await access('public'+image.path);await access('public'+image.thumb);assert(image.width>0&&image.height>0);}}
for(const file of ['site.js','gallery.js','gallery-motion.js','contact.js','careers.js','video.js'])execFileSync(process.execPath,['--check','public/'+file]);
for(const file of ['index','karriere','impressum','datenschutz',...projects.map(p=>'projekte/'+p.id)]){const html=await readFile('public/'+file+'.html','utf8');assert(html.includes('noindex,nofollow'));assert(!/mehlig|Moorrege|85943/.test(html));for(const match of html.matchAll(/(?:src|href)="(\/[^"?#]*)(?:[?#][^"]*)?"/g)){const path=match[1];await access('public'+(path==='/'?'/index.html':/\.[^/]+$/.test(path)?path:path+'.html'));}}
const module=await import('../dist/worker.mjs?check='+Date.now());let assetRequest;
const env={ASSETS:{fetch:async request=>{assetRequest=request;return new Response('range',{status:206,headers:{'Content-Type':'video/mp4','Content-Range':'bytes 0-4/3172418'}})}}};
for(const path of ['/','/karriere','/impressum','/datenschutz','/projekte/berliner-tor']){const r=await module.default.fetch(new Request('https://test.invalid'+path),env);assert.equal(r.status,200);assert(r.headers.get('Content-Security-Policy').includes("media-src 'self'"));assert(r.headers.get('Cache-Control').includes('must-revalidate'));}
const range=await module.default.fetch(new Request('https://test.invalid/assets/video/hero.mp4',{headers:{Range:'bytes=0-4'}}),env);assert.equal(range.status,206);assert.equal(assetRequest.headers.get('Range'),'bytes=0-4');assert.equal(range.headers.get('Content-Range'),'bytes 0-4/3172418');
assert.equal((await module.default.fetch(new Request('https://test.invalid/missing'),env)).status,404);assert.equal((await module.default.fetch(new Request('https://test.invalid/',{method:'POST'}),env)).status,405);assert.equal(await(await module.default.fetch(new Request('https://test.invalid/',{method:'HEAD'}),env)).text(),'');
console.log('Checked: 6 projects + 9 insight collections / 31 photos, 7 contacts, all local links, script syntax, routes, CSP and video Range forwarding.');
const fallback={ASSETS:{fetch:async()=>new Response(Uint8Array.from([0,1,2,3,4,5,6,7,8,9]),{headers:{'Content-Type':'video/mp4',ETag:'"original"'}})}};
for(const [requested,status,expected]of [['bytes=2-4',206,[2,3,4]],['bytes=-3',206,[7,8,9]],['bytes=8-',206,[8,9]],['bytes=10-',416,[]],['bytes=-0',416,[]]]){const r=await module.default.fetch(new Request('https://test.invalid/assets/video/film.mp4',{headers:{Range:requested}}),fallback);assert.equal(r.status,status);assert.deepEqual([...new Uint8Array(await r.arrayBuffer())],expected);}
assert.equal((await module.default.fetch(new Request('https://test.invalid/assets/video/film.mp4',{headers:{Range:'bytes=2-4','If-Range':'"old"'}}),fallback)).status,200);
console.log('Checked native and fallback video byte ranges, suffix ranges, invalid ranges and If-Range.');
